#!/usr/bin/env php
<?php

(new randomFile($argv));

class randomFile {
    public function __construct(array $args)
    {
        $allFiles = [];
        $storedFiles = [];

        $configData = file_get_contents('./etc/config.json');
        $config = json_decode($configData, true);

        $group = $args[1] ?? key($config['directories']);

        foreach ($config['directories'][$group] as $directory) {
            $paths = self::returnPaths(self::readDirectory($directory, true));
            $allFiles = array_merge($allFiles, $paths['file']);
        }

        $generated = file_get_contents('./var/storage.json');
        $storage = json_decode($generated, true);

        foreach ($storage as $files) {
            $storedFiles[] = $files['path'];
        }

        $cleared = array_diff($allFiles, $storedFiles);

        $numberOfFiles = count($cleared);
        $rand = random_int(1, $numberOfFiles);

        $randFile = $allFiles[$rand -1];

        $storage[] = [
            'date' =>date('d-m-Y H:i:s'),
            'path' => $randFile,
        ];

        $newStorage = json_encode($storage, JSON_UNESCAPED_SLASHES | JSON_PRETTY_PRINT);
        file_put_contents('./var/storage.json', $newStorage);

        echo "\n" . $randFile . "\n";
    }

    /**
     * read directory content, (optionally all sub folders)
     *
     * @param string $path
     * @param boolean $whole
     * @return array|null
     * @example readDirectory('dir/some_dir')
     * @example readDirectory('dir/some_dir', TRUE)
     * @example readDirectory(); - read MAIN_PATH destination
     */
    static function readDirectory(string $path, bool $whole = false) : array
    {
        $list = [];

        if (!self::exist($path)) {
            return $list;
        }

        $iterator = new DirectoryIterator($path);

        /** @var DirectoryIterator $element */
        foreach ($iterator as $element) {
            if ($element->isDot()) {
                continue;
            }

            if ($whole && $element->isDir()) {
                $list[$element->getRealPath()] = self::readDirectory(
                    $element->getRealPath(),
                    true
                );
            } else {
                $list[$element->getRealPath()] = $element->getFileInfo();
            }

        }

        return $list;
    }

    /**
     * transform array wit directory/files tree to list of paths grouped on files and directories
     *
     * @param array $array array to transform
     * @param boolean $reverse if TRUE revert array (required for deleting)
     * @internal param string $path base path for elements, if emty use paths from transformed structure
     * @return array array with path list for files and directories
     * @example returnPaths($array, '')
     * @example returnPaths($array, '', TRUE)
     * @example returnPaths($array, 'some_dir/dir', TRUE)
     */
    static function returnPaths(array $array, bool $reverse = false) : array
    {
        if ($reverse) {
            $array = array_reverse($array);
        }

        $pathList = [];

        foreach ($array as $path => $fileInfo) {
            if (is_dir($path)) {

                $list = self::returnPaths($fileInfo);
                foreach ($list as $element => $value) {

                    if ($element === 'file') {
                        foreach ($value as $file) {
                            $pathList['file'][] = $file;
                        }
                    }

                    if ($element === 'dir') {
                        foreach ($value as $dir) {
                            $pathList['dir'][] = $dir;
                        }
                    }

                }
                $pathList['dir'][] = $path;

            } else {
                /** @var DirectoryIterator $fileInfo */
                $pathList['file'][] = $fileInfo->getRealPath();
            }
        }

        return $pathList;
    }

    /**
     * check that file exists
     *
     * @param string $path
     * @return boolean TRUE if exists, FALSE if not
     */
    static function exist(string $path) : bool
    {
        return file_exists($path);
    }
}
